# Generated by Django 3.1.12 on 2021-08-17 16:21

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='If you need some clue about how to fill this, please see https://en.wikipedia.org/wiki/Escoba', max_length=400)),
                ('published_by', models.CharField(max_length=400)),
                ('origin', models.CharField(max_length=400)),
                ('type', models.CharField(max_length=400)),
                ('players', models.CharField(max_length=400)),
                ('number_of_cards', models.IntegerField()),
                ('deck', models.CharField(max_length=400)),
                ('play', models.CharField(max_length=400)),
                ('playing_time', models.CharField(max_length=400)),
                ('description', tinymce.models.HTMLField(blank=True, help_text='Separate your explanation in paragraphs if needed.', null=True)),
                ('visible', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('documentation', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('P', 'Partial (need explanation in notes)'), ('Unavailable', 'Unavailable')], max_length=11)),
                ('supported_rules', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('P', 'Partial (need explanation in notes)'), ('Unavailable', 'Unavailable')], max_length=11)),
                ('single_player', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('P', 'Partial (need explanation in notes)'), ('Unavailable', 'Unavailable')], max_length=11)),
                ('multiplayer', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('P', 'Partial (need explanation in notes)'), ('Unavailable', 'Unavailable')], max_length=11)),
                ('notes', tinymce.models.HTMLField(blank=True, help_text='<p>Please insert the explanation here. You can put bullets to clarify your explanation: </p><ul><li>This rule is not implemented</li><li>This feature needs to be polished</li></ul>', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_game', to='main.game')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_variant', to='main.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='If you need some clue about how to fill this, please see https://en.wikipedia.org/wiki/Escoba', max_length=50)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_photo/')),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('alt', models.CharField(blank=True, max_length=400, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_objective', to='main.game')),
            ],
        ),
    ]
