# Generated by Django 3.1.12 on 2021-08-20 10:04

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRegulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='If you need some clue about how to fill this, please see https://en.wikipedia.org/wiki/Escoba', max_length=50)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_photo/')),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('alt', models.CharField(blank=True, max_length=400, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orig_game', to='main.game')),
            ],
        ),
        migrations.DeleteModel(
            name='GameObjective',
        ),
    ]
