# Generated by Django 3.1.12 on 2021-08-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210820_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameregulation',
            name='title',
            field=models.CharField(help_text='If you need some clue about how to fill this, please see https://en.wikipedia.org/wiki/Escoba', max_length=100),
        ),
    ]
