# Generated by Django 3.1.12 on 2021-09-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210820_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameregulation',
            old_name='alt',
            new_name='regulation_alt',
        ),
        migrations.RenameField(
            model_name='gameregulation',
            old_name='caption',
            new_name='regulation_caption',
        ),
        migrations.RenameField(
            model_name='gameregulation',
            old_name='description',
            new_name='regulation_description',
        ),
        migrations.RenameField(
            model_name='gameregulation',
            old_name='image',
            new_name='regulation_image',
        ),
        migrations.RenameField(
            model_name='gameregulation',
            old_name='title',
            new_name='regulation_title',
        ),
    ]
