# Generated by Django 3.1.12 on 2021-09-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210901_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameregulation',
            old_name='regulation_alt',
            new_name='alt',
        ),
        migrations.RenameField(
            model_name='gameregulation',
            old_name='regulation_caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='gameregulation',
            old_name='regulation_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='gameregulation',
            old_name='regulation_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='gameregulation',
            old_name='regulation_title',
            new_name='title',
        ),
    ]
