# Generated by Django 3.1.12 on 2021-09-01 15:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210901_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Separate your explanation in paragraphs if needed. Tables are not allowed here at the moment.', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, help_text='<p>Please insert the explanation here. You can put bullets to clarify your explanation: </p><ul><li>This rule is not implemented</li><li>This feature needs to be polished</li></ul><p><b>Note:</b> Tables are not allowed here.</p>', null=True),
        ),
        migrations.AlterField(
            model_name='gameregulation',
            name='description',
            field=tinymce.models.HTMLField(help_text="<p>Please insert the explanation here. If you insert a table, please make sure that the font is 'System Font' and there is no font styling (font-size: small or font-size:16px...) in each row when saving it.</p><p><b>Note:</b> In case there is such issue, you can install FoxReplace on Firefox, search each font style and replacing them all by nothing.</p>"),
        ),
    ]
